type = "Wham"
entrypoint = "wham.dweam_game:WhamGame"
repo_link = "https://huggingface.co/microsoft/wham"
thumbnail_dir = "thumbnails"

# Game-specific metadata
[games.wham]
title = "Wham"
tags = ["MOBA"]
description = "Microsoft's WHAM model, for game ideation."

[games.wham.buttons]
"â¬†ï¸ Up" = "Arrow Up"
"â¬…ï¸ Left" = "Arrow Left"
"â¬‡ï¸ Down" = "Arrow Down"
"â¡ï¸ Right" = "Arrow Right"
"ğŸ”¨ Interact" = "Z"
"ğŸ”„ Reset" = "Enter"
